name: IP from webpages

on:
  push:
  schedule:
    - cron: '0 12 * * *'  # 每天中午 12 点运行

env:
  WEB_PAGES: |-
    https://github.com/w1282155089/cf-speed-dns/blob/main/index.html
    https://github.com/woniu336/cf-speed-dns/blob/main/index.html
    https://github.com/XCQ0607/cf-speed-dns/blob/main/index.html
    https://github.com/gaoshi22/cf-speed-dns/blob/main/index.html
    https://github.com/yuhb1975/cf-speed-dns/blob/main/index.html

jobs:
  extract_ip_addresses:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install requests

      - name: Extract IP addresses
        id: extract_ip
        run: |
          import requests
          import re

          ip_addresses = []

          for url in env.WEB_PAGES.splitlines():
            response = requests.get(url)
            ip_regex = re.compile(r'\b(?:\d{1,3}\.){3}(?:\d{1,3})\b')
            ip_addresses.extend(ip_regex.findall(response.text))

          with open('ip.txt', 'w') as f:
            f.write('\n'.join(ip_addresses))

      - name: Display extracted IP addresses
        run: |
          cat ip.txt

      - name: Upload extracted IP addresses as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ip-addresses
          path: ip.txt
